class Matn {
  String matn;

  Matn(this.matn);
}

class MatnServise {
  List<Matn> uzunMatn = [
    Matn(//0
        "Yoʻlbars (lot. Panthera tigris) — mushuksimonlar oilasiga mansub yirtqich sut emizuvchi hayvon. Katta mushuklar (lot. Pantherinae) ostoilasiga kiruvchi Panthera urugʻining beshta turidan biri. Shu oilaning eng yirik vakili. Yoʻlbars umuman quruqlikdagi eng yirik yirtqichlardan biri, vazni bo'yicha faqat oq ayiq va qoʻngʻir ayiqdan kichik. Yoʻlbarsning ikkta zamonaviy ostturi aniqlab ajratilgan. Bu ikki osttur toʻqqizta populyatsiyani oʻz ichiga oladi. XXI asr boshiga faqat oltitasi saqlanib qolgan. Yolbarslarning umumiy soni 2600-3900 boshdan iborat[1]. Bengal yoʻlbarsi populyatsiyasi eng koʻp boshdan iborat, yoʻlbarslarning umumiy populyatsiyasing 40% tashkil qiladi. XX asrda Tabiat va tabiy resurslarni muhofaza qilish xalqaro ittifoqi qizil kitobiga kiritildi. Shu bilan bir qatorda turli davlatlar qizil kitobiga va himoya hujjatlariga kiritilgan. 2020-yil holatiga koʻra yoʻlbarslarni butun dunyoda ovlash taqiqlangan"),


    Matn(//1
        "Ayiqlar (Ursidae) — yirtqichlar turkumiga mansub sut emizuvchilar oilasi. Eng yirik yirtqichlar, boshi katta, boʻyni qisqa va yoʻgʻon. Panjalari kuchli rivojlangan, tovonida yuradi. Dumi kalta, kalin juni orasida deyarli sezilmaydi. Koʻpchilik ayiqlar oʻsimlikxoʻr yoki aralash oziqlanadi. Ayiqlar odamga tegmaydi. Faqat oziq tanqis boʻlganida, keksa va yarador ayiqlar odam uchun xavfli hisoblanadi. Oq ayiq esa haqiqiy yirtqich boʻlib, odam uchun xavfli. Ayiqlarning 4 uruqqa mansub 7 turi mavjud. Qoʻngʻir ayiq (Ursus arctos) Yevropa, Osiyo, Shimoliy Afrika va Amerikaning oʻrmonli oʻlkalarida tarqalgan. Tanasining uz. 2,5 m, ogʻirligi baʼzan 750 kg ga yetadi. Oʻzbekistonning togʻ oʻrmonlarida oqtirnoqli qoʻngʻir ayiq (U. arctos leuconyx) uchraydi. Qoʻngʻir ayiq okt,- noyabrdan mart — aprelgacha daraxtlar kovagi, toshlarning ostidagi kovaklarda, tabiiy chuqur joylar yoki oʻzi qazigan iniga tushib qishki uyquga ketadi. "),
    Matn(//2
        'Arslon yoki sher (lotincha: Panthera leo) mushuksimonlar oilasiga mansub turdir. Uzunligi 240 sm gacha (urgʻochisi kichikroq), ogʻirligi 280 kg gacha boʻladi. Yuz qismi choʻziq, dumining uchida uzun qora qildan iborat popugi bor. Tanasi kalta jun bilan qoplangan, erkaklari tanasining oldingi qismi (boʻyni, koʻkragi va yuzi)dagi uzun yunglari yolni hosil qiladi. Rangi sargʻish, yoli qoramtir tusda. Qadimgi areali Afrika (gʻarbidan tashqari), Yevropa (Bolqon yarim oroli, Zakavkaze — Armaniston) hamda Osiyoni (Arabiston yarim oroli, Kichik, Old va Janubiy Osiyo — Sharqda Hindistongacha) oʻz ichiga olgan. Individlar soni va areali keskin kamayib ketgan, hozirgi areali asosan Markaziy Afrikaning qoʻriqlanadigan hududlari va qisman Janubiy Osiyodan iborat.Arslon choʻl, savanna va daryo yaqinidagi oʻrmonlarda istiqomat qiladi. Poligam, oilaviy guruh hosil qiladi. Har 2 yilda bir marta 3—4 tadan bolalaydi. Homiladorlik davri 4—5 oy, 6—7 yoshida voyaga yetadi, erkagidan 3 yoshda yol chiqadi. Arslon kechasi guruh boʻlib ov qiladi, yirik tuyoqli hayvonlarni ovlaydi. Qari va yarador arslon odamga ham hujum qilishi mumkin. 70 yilgacha yashaydi. Arslon hamma joyda muhofaza qilinadi; hind kenja turi (P. L. persica) Tabiatni muhofaza qilish xalqaro tashkilot Qizil kitobiga kiritilgan.'),
    Matn(//3
        'Gepard (Acinonyx jubatus) — mushuksimonlar oilasiga mansub yirtqich sut emizuvchi, gepardlar (Acinonyx) ypygʻining yagona turi. Tanasining uz. 123— 150 sm, dumi 63—75 sm. Oyoqlari uzun va ingichka, tirnoqlari ichkariga tortilmasligi bilan boshqa mushuksimonlardan farq qiladi. Yungi sargʻish qum rangda, mayda qora dogʻlar bilan tekis qoplangan. Bolalari tanasining ustki tomonidagi uzun tik yunglari paxmoq mantiya (yopingʻich) hosil qiladi. Afrika, Jan.-gʻarbiy Osiyo (Eron, Afgʻoniston, Balujiston) va Oʻrta Osiyoda tarqalgan. 1972-yilgacha onda-sonda Turkmanistonning jan.da uchrab turardi. Kunduzi hayot kechiradi. Homiladorligi 84-95 soʻtka. 2-4 ta bola tugʻadi. Toʻqay, dasht, choʻl va togʻ etaklarida yashaydi. Tuyoqli hayvonlar (kiyiklar, qoʻylar)ni ov qiladi. Oʻljasiga pana joydan tashlanadi va qisqa masofada quvib yetadi (tezligi soatiga 110 km gacha). Qadimda qoʻlga oʻrgatilgan G. dan ov qilishda foydalanilgan. Hozir soni juda kamayib ketgan, tabiatda butun dunyo boʻyicha bir necha yuzta saqlanib qolgan. Oʻzbekistan Respublikasi va Xalqaro Kizil kitobga kiritilgan. Tutqunlikda yaxshi koʻpayadi.'),
    Matn(//4
        'Akulalar (Selachomorpha) — togʻayli baliqlar sinfi plastinka jabralilar kenja sinfining katta turkumi. Tanasi suyri shaklda, suv tubida yashovchi akulalar yassi, uz. 15-40 sm dan (tikanli qora akulalar) 15-20 m gacha (gigant akulalar), ogʻirligi 14 t gacha (gigant va kit akulalar). Tanasi plakoid tangachalar bilan krplangan. Jabra yoriqlari 5 (baʼzi turlarida 6-7) tadan boʻlib, boshining ikki yonida, ogʻzi boshining ostida tanasiga koʻndalang joylashgan. Dum suzgichi kuchli rivojlangan, har xil kattalikdagi (gsterotserkal) ikkita boʻlakdan iborat. Tishlari koʻp, uchi oʻtkir. Yirtqich akulalarning tishlari juda yirik. Koʻpchilik akulalar yirtqich; baliqlar, mollyuskalar va boshqa hayvonlar bilan, kit va gigant akulalar esa plankton bilan oziqlanadi. Akulalar tuxumdan tirik tugʻadi yoki tuxum qoʻyib koʻpayadi. Akulalar 6 turkumni (har xil tishlilar, koʻp jabralilar, lamnosimonlar, katransimonlar, arraburunsimonlar, skvatinsimonlar), 20 oilani oʻz ichiga oladi. Akulalar Orol va Kaspiy dengizidan boshqa hamma dengiz va okeanlarda, ayrim turlari chuchuk suv havzalari (Gang va Amazonka daryolari, Nikaragua koʻli)da yashaydi. Qora va Uzoq Sharq dengizlarida tikanli qora akulalar, yaʼni katran, Shimoliy va Uzoq Sharq dengizlarida seld akulalar, shim. dengizlarda qutb akulalar tarkalgan.'),
 ];

Matn getUzunMatn(int index) {
  return uzunMatn[index];
}
}
